### ISSUE TITLE
Reconsider `lines_longer_than_80_chars`

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/effective_dart#13]
I would like to discuss and maybe reconsider adding the [`lines_longer_than_80_chars`](https://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html) lint rule.

This package should aim to follow the Effective Dart guide **as much as possible** and disabling this lint rule is probably *opinionated*. Given the fact that you can easily [suppress](https://github.com/tenhobi/effective_dart#suppressing-lints) any lint rule per project, file or line, I would like to reconsider this and add it to the lints we use.

Cc @felangel as you have for now the biggest projects using this package.

**Comment by felangel** [comment]
I agree that the rule should be added because as you mentioned the goal should be to match effective dart rules as closely as possible and people can always disable individual rules.
