### ISSUE TITLE
conflicting advice for imports?

### ISSUE THREAD

**Issue by pq** [tenhobi/effective_dart#26]
Hi!

Looking at advice for imports, it looks like we're suggesting conflicting rules:

https://github.com/tenhobi/effective_dart/blob/7a3e4a87ee3589ef38168216bcd0200602e20a8d/lib/analysis_options.1.2.0.yaml#L23-L24

Or maybe the docs need to be updated?

**Comment by tenhobi** [comment]
Hi, those are not conflicting rules, actually. :-) I have also explored that. The naming is quite confising.

http://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html

This says "don't use `../lib/` in your relative imports".

http://dart-lang.github.io/linter/lints/prefer_relative_imports.html

This says "prefer relative imports over absolute ones".

---

Its both part of https://dart.dev/guides/language/effective-dart/usage#prefer-relative-paths-when-importing-libraries-within-your-own-packages-lib-directory

**Comment by pq** [comment]
Looks like we could make the docs a little clearer.  Thanks!
