### ISSUE TITLE
Constructor documentation as "public API"

### ISSUE THREAD

**Issue by Lootwig** [tenhobi/effective_dart#29]
Please feel free to direct me to a better suited place for this! I did not find any other place for discussion on these guidelines. (SO maybe?)

The `public_member_api_docs` also applies to constructors. What use is a "Creates an instance of this class" docstring, really? Especially for parameterless constructors that are just performing initializion etc.?

**Comment by tenhobi** [comment]
That depends. I am not the author of these rules. Some people don't comment at all and use ignore, or some use macros to copy class comment there, see https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/bloc.dart
