### ISSUE TITLE
Any option to toggle rules

### ISSUE THREAD

**Issue by apgapg** [tenhobi/effective_dart#3]
Thanks for this cool package.
Can we disable some rules like 'Document all public members' ?

**Comment by apgapg** [comment]
Done. I added this in analysis file
```
linter:
  rules:
    public_member_api_docs: false
```

**Comment by tenhobi** [comment]
Hi @apgapg ✋, thanks for oppening an issue.

Does this works? I will check that and add a note to the READE.

**Comment by apgapg** [comment]
Yes it worked. Thanks for this package. I can now test tablet and phone UI simultaneously on flutter desktop. This prevents me to open 2 simulator simultaneously

**Comment by tenhobi** [comment]
Cool. Thx for bringing it up. I will update docs later today. 👍
