### ISSUE TITLE
Implement (missing?) period at end of doccomment

### ISSUE THREAD

**Issue by ALMaclaine** [tenhobi/effective_dart#30]
I'm not sure if this was missed or not in scope of the project but would you consider adding it?

https://dart.dev/guides/language/effective-dart/documentation#do-format-comments-like-sentences

Thank you

**Comment by ALMaclaine** [comment]
nvm I realized I should check the linter rules and see it is not an option, my apologies.

**Comment by tenhobi** [comment]
Hi, no problem. (: As you mentioned, there is no lint rule for that.
