### ISSUE TITLE
Update badge in packages that depend on effective_dart

### ISSUE THREAD

**Issue by tenhobi** [tenhobi/effective_dart#33]
Update badge in packages that depend on effective_dart, ergo changing URL from GitHub to Pub, to remove the dependency to this repository URL in case sometimes it gets transformed.

- [ ] Bloc
- [ ] Equatable
- [x] Hydrated Bloc (felangel/hydrated_bloc#59)
- [ ] ...

New badge markdown:

```
[![style: effective dart](https://img.shields.io/badge/style-effective_dart-40c4ff.svg)](https://pub.dev/packages/effective_dart)
```

**Comment by zepfietje** [comment]
- [x] Hydrated Bloc (https://github.com/felangel/hydrated_bloc/pull/59)
