### ISSUE TITLE
Add async related rules

### ISSUE THREAD

**Issue by devjeff** [tenhobi/effective_dart#34]
I wan to suggest to add the following rules to the effective dart analysis options:

- avoid_void_async
- await_only_futures

I find these lint rules extremely important as the helped me to find and avoid multiple issues in cases where you simply forget to add the async keyword to a method definition and try to await the result, although the method isn't really executed asynchronously. I can not think of a case where it would be reasonable to omit these rules.

**Comment by tenhobi** [comment]
Hello @devjeff ✋,
this package only reflect official Effective Dart rules, so I cannot simply add a new rule. You can open an issue probably in https://github.com/dart-lang/linter

Thanks anyway!

**Comment by devjeff** [comment]
Ok. I see. Thanks for your hint.
