### ISSUE TITLE
How to automatically apply changes in auto formatting?

### ISSUE THREAD

**Issue by pedrolemoz** [tenhobi/effective_dart#36]
Hello! I would like to know how to put certain actions to be executed automatically when the auto formatter is used.

I'm currently using VS Code, and I would like all my imports to be changed to relative imports, and then, automatically organized. Any idea how to do this?

**Comment by tenhobi** [comment]
Hi, that is not possible at the moment I think. Anyhow, try to ask in linter or vs code's dart plugin repo for this feature?

**Comment by pedrolemoz** [comment]
Hi! I found an extension for VS Code that do this job. It's called dart-import. You can find the repo here: https://github.com/luanpotter/vscode-dart-import, and the extension in marketplace: https://marketplace.visualstudio.com/items?itemName=luanpotter.dart-import
