### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by isorensen** [tenhobi/effective_dart#40]
Hello! thanks for the awesome package.

Dart 2.12 and flutter 2.0.0 are now in stable with the null-safety feature.

Migrating this package to null-safety would help a lot. :)

**Comment by tenhobi** [comment]
Hi @isorensen, this project doesn't contain any code. I haven't checked, should I do something else? 🤔

**Comment by tenhobi** [comment]
Found it. https://dart.dev/null-safety/migration-guide It should be migrated. Thanks for the tip! 👍

**Comment by tenhobi** [comment]
![image](https://user-images.githubusercontent.com/5287596/110305579-1e7e9e00-7ffd-11eb-8edd-bfe9ffe0b779.png)

![](https://media1.giphy.com/media/TdfyKrN7HGTIY/giphy.gif)
