### ISSUE TITLE
[proposal] consider adding `avoid_dynamic_calls`

### ISSUE THREAD

**Issue by iapicca** [tenhobi/effective_dart#41]
as for the title, please consider adding the experimental lint [avoid_dynamic_calls](https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html)
thank you

**Comment by tenhobi** [comment]
Hi @iapicca,
this package only provides the actual list of rules according to the [Effective Dart guide](https://dart.dev/guides/language/effective-dart). Try to open an issue maybe in site-www https://github.com/dart-lang/site-www or linter https://github.com/dart-lang/linter, I am not sure. :-)
