### ISSUE TITLE
Fix in all files 

### ISSUE THREAD

**Issue by apgapg** [tenhobi/effective_dart#9]
Hi @tenhobi, 
I got an warning 'add curly braces to all if and else statements' in intellij on a line. When i press quick fix it, it fixed it for that particular line. Its very difficult to add curly braces to every if else in my flutter application. 
Is there a way to fix all files instead of fixing that current line in one go?
I remember in eslint it gave an option to fix for all files.

**Comment by tenhobi** [comment]
Hi @apgapg ✋, thanks for opening an issue!

Note that applying all suggestions for a whole project/file could be dangerous.

But in IntelliJ there might be a fix-all option, not sure if that will be applied for this lint tho.

![image](https://user-images.githubusercontent.com/5287596/68369205-02819880-013a-11ea-83b1-bc6ab0657a76.png)

---

Note: I tried to do this, but it is not unfortunately possible. :/

![image](https://user-images.githubusercontent.com/5287596/68369988-cbac8200-013b-11ea-8cc9-2002766bdc27.png)

**Comment by tenhobi** [comment]
It might be easier to open Analyser warnings in Tool Windows Bars (tab on the bottom of the tab, or if hidden, it appears after pressing ALT). At least something...
